# Libaray Load

In [1]:
import pandas as pd
import numpy as np
import requests
from tqdm import tqdm
from pyproj import Proj, Transformer
from scipy.spatial import cKDTree

# 관측소 데이터 가져오기

In [2]:
aa=pd.DataFrame()
for node in range(0,6):
    # 요청 변수
    params = {
        "basin": f"{node}",       # 한강
        "oper": "y",        # 운영중
      #  "mngorg": "1",      # 기후에너지환경부
        "output": "json"    # JSON 형식
    }

    # API URL
    url = "http://www.wamis.go.kr:8080/wamis/openapi/wkw/wl_dubwlobs"

    # 요청
    response = requests.get(url, params=params)

    # 상태 확인
    if response.status_code == 200:
        data = response.json()  # JSON 파싱
        obs_list = data.get("list", [])  # 관측소 리스트
        df = pd.DataFrame(obs_list)
        print(df.head())
    else:
        print("API 요청 실패:", response.status_code)
    aa=pd.concat([aa,df],axis=0)

Empty DataFrame
Columns: []
Index: []
  bbsnnm    obscd     obsnm clsyn obsknd  sbsncd    mngorg
0     한강  1001602  평창군(송정교)    운영    T/M  100108  기후에너지환경부
1     한강  1001603  태백시(무사교)    운영    T/M  100101   한국수자원공사
2     한강  1001605      송천1교    운영    T/M  100105   한국수력원자력
3     한강  1001607  삼척시(번천교)    운영    T/M  100101   한국수자원공사
4     한강  1001613  삼척시(광동교)    운영    T/M  100102   한국수자원공사
  bbsnnm    obscd      obsnm clsyn obsknd  sbsncd    mngorg
0    낙동강  2001608  태백시(보드미교)    운영    T/M  200101  기후에너지환경부
1    낙동강  2001610   태백시(문화교)    운영    T/M  200101  기후에너지환경부
2    낙동강  2001613   태백시(루사교)    운영    T/M  200101   한국수자원공사
3    낙동강  2001615   봉화군(대현교)    운영    T/M  200102  기후에너지환경부
4    낙동강  2001625   봉화군(광회교)    운영    T/M  200103  기후에너지환경부
  bbsnnm    obscd       obsnm clsyn obsknd  sbsncd    mngorg
0     금강  3001605    장수군(운곡교)    운영    T/M  300101  기후에너지환경부
1     금강  3001610  장수군(장계시장교)    운영    T/M  300102  기후에너지환경부
2     금강  3001615          천천    운영     보통  300104   한국수자원공사
3     금강  3001616   장수군(오봉1교)    운영    T/M  300104  기후에너지환경부
4     금강  3001620    장수군(연화교)    운영    T/M  300104   한국수자원공사
  bbsnnm    obscd       obsnm clsyn obsknd  sbsncd    mngorg
0    섬진강  4001605    진안군(마령교)    운영    T/M  400101  기후에너지환경부
1    섬진강  4001610    진안군(좌포교)    운영    T/M  400103  기후에너지환경부
2    섬진강  4001613    임실군(주천교)    운영    T/M  400103  기후에너지환경부
3    섬진강  4001617  임실군(무등제1교)    운영    T/M  400104  기후에너지환경부
4    섬진강  4001620    임실군(호암교)    운영    T/M  400105   한국수자원공사
  bbsnnm    obscd      obsnm clsyn obsknd  sbsncd    mngorg
0    영산강  5001610   담양군(담양댐)    운영    T/M  500103  기후에너지환경부
1    영산강  5001615   담양군(금월교)    운영    T/M  500103  기후에너지환경부
2    영산강  5001616  담양군(중방4교)    운영    T/M  500103   한국수자원공사
3    영산강  5001618   담양군(장천교)    운영    T/M  500103   한국수자원공사
4    영산강  5001620   담양군(덕용교)    운영    T/M  500102  기후에너지환경부

In [3]:
aa.reset_index(drop=True,inplace=True)

In [4]:
aa

     bbsnnm    obscd     obsnm clsyn obsknd  sbsncd    mngorg
0        한강  1001602  평창군(송정교)    운영    T/M  100108  기후에너지환경부
1        한강  1001603  태백시(무사교)    운영    T/M  100101   한국수자원공사
2        한강  1001605      송천1교    운영    T/M  100105   한국수력원자력
3        한강  1001607  삼척시(번천교)    운영    T/M  100101   한국수자원공사
4        한강  1001613  삼척시(광동교)    운영    T/M  100102   한국수자원공사
...     ...      ...       ...   ...    ...     ...       ...
1182  영산강서해  5301660  고창군(부정교)    운영    T/M  530103  기후에너지환경부
1183  영산강서해  5301690  고창군(용선교)    운영    T/M  530103  기후에너지환경부
1184  영산강서해  5302620  영광군(반와교)    운영    T/M  530203  기후에너지환경부
1185  영산강서해  5302640        불갑    운영    T/M  530204   한국농어촌공사
1186  영산강서해  5302660  영광군(외간교)    운영    T/M  530204  기후에너지환경부

[1187 rows x 7 columns]

In [5]:
vv=pd.DataFrame()
for node in range(0,1187):
    num=aa['obscd'][node]
    # 요청 변수
    params = {
        "obscd": num,       # 한강
        "output": "json"    # JSON 형식
    }

    # API URL
    url = "http://www.wamis.go.kr:8080/wamis/openapi/wkw/wl_obsinfo"

    # 요청
    response = requests.get(url, params=params)

    # 상태 확인
    if response.status_code == 200:
        data = response.json()  # JSON 파싱
        obs_list = data.get("list", [])  # 관측소 리스트
        df = pd.DataFrame(obs_list)
        print(df.head())
    else:
        print("API 요청 실패:", response.status_code)
    vv=pd.concat([vv,df],axis=0)

스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
      obsnm             obsnmeng  wlobscd    mggvcd bbsncd  sbsncd  \
0  울산시(웅촌교)  Ulsansi(Ungchongyo)  2301625  기후에너지환경부  회야ㆍ수영  230102

     obsopndt obskdcd rivnm bsnara  ...     tmx     tmy     gdt   wltel tdeyn  \
0  2025-01-01     T/M   곡천천  19.38  ...  400230  220088  49.419  60.156     N

  mxgrd sistartobsdh  siendobsdh olstartobsdh olendobsdh
0  None   2025010100  2025101622     20241231   20251016

[1 rows x 27 columns]
      obsnm               obsnmeng  wlobscd    mggvcd bbsncd  sbsncd  \
0  울산시(통천교)  Ulsansi(Tongcheongyo)  2301630  기후에너지환경부  회야ㆍ수영  230102

     obsopndt obskdcd rivnm bsnara  ...     tmx     tmy    gdt  wltel tdeyn  \
0  1962-07-01     T/M   회야강  112.8  ...  403251  221544  33.72  38.95     N

  mxgrd sistartobsdh  siendobsdh olstartobsdh olendobsdh
0     5   2006010916  2025101622     19630101   20251016

[1 rows x 27 columns]
      obsnm                obsnmeng  wlobscd    mggvcd bbsncd  sbsncd  \
0  울산시(청백교)  Ulsansi(Cheongbaekgyo)  2301645  기후에너지환경부  회야ㆍ수영  230101

     obsopndt obskdcd rivnm bsnara  ...     tmx     tmy    gdt  wltel tdeyn  \
0  2025-01-01     T/M   청량천  35.67  ...  409555  222769  -1.03  7.668     N

  mxgrd sistartobsdh  siendobsdh olstartobsdh olendobsdh
0  None   2025010100  2025101622     20241231   20251016

[1 rows x 27 columns]
      obsnm              obsnmeng  wlobscd    mggvcd bbsncd  sbsncd  \
0  울산시(동천리)  Ulsansi(Dongcheonri)  2301650  기후에너지환경부  회야ㆍ수영  230103

     obsopndt obskdcd rivnm  bsnara  ...     tmx     tmy    gdt   wltel tdeyn  \
0  1962-07-01     T/M  None  129.81  ...  407414  220914  5.522  16.484     N

  mxgrd sistartobsdh  siendobsdh olstartobsdh olendobsdh
0     8   2006010916  2025101622     19630101   20251016

[1 rows x 27 columns]
      obsnm             obsnmeng  wlobscd    mggvcd bbsncd  sbsncd  \
0  울산시(덕신교)  Ulsansi(Deoksingyo)  2301670  기후에너지환경부  회야ㆍ수영  230103

     obsopndt obskdcd rivnm  bsnara  ...     tmx     tmy    gdt  wltel tdeyn  \
0  2016-01-01     T/M  None  137.18  ...  409295  217705  -1.46  10.76     N

  mxgrd sistartobsdh  siendobsdh olstartobsdh olendobsdh
0  None   2016010100  2025101622     20151231   20251016

[1 rows x 27 columns]
       obsnm               obsnmeng  wlobscd    mggvcd bbsncd  sbsncd  \
0  울산시(남창3교)  Ulsansi(Namchang3gyo)  2301680  기후에너지환경부  회야ㆍ수영  230103

     obsopndt obskdcd rivnm bsnara  ...     tmx     tmy    gdt  wltel tdeyn  \
0  2025-01-01     T/M   남창천  40.64  ...  407477  215534  1.044  7.795     N

  mxgrd sistartobsdh  siendobsdh olstartobsdh olendobsdh
0  None   2025010100  2025101622     20241231   20251016

[1 rows x 27 columns]
        obsnm                 obsnmeng  wlobscd    mggvcd bbsncd  sbsncd  \
0  부산시(회동저수지)  Busansi(Hoedongjeosuji)  2302635  기후에너지환경부  회야ㆍ수영  230202

     obsopndt obskdcd rivnm bsnara  ...     tmx     tmy gdt   wltel tdeyn  \
0  2024-01-09     T/M  None  99.54  ...  392811  195346   0  40.912     N

  mxgrd sistartobsdh  siendobsdh olstartobsdh olendobsdh
0  None   2024020212  2025101622     20240202   20251016

[1 rows x 27 columns]
      obsnm               obsnmeng  wlobscd    mggvcd bbsncd  sbsncd  \
0  부산시(동천교)  Busansi(Dongcheongyo)  2302640  기후에너지환경부  회야ㆍ수영  230203

     obsopndt obskdcd rivnm  bsnara  ...     tmx     tmy   gdt wltel tdeyn  \
0  2022-03-02     T/M   수영강  104.17  ...  392881  193282  -1.4  9.59     N

  mxgrd sistartobsdh  siendobsdh olstartobsdh olendobsdh
0  None   2022021115  2025101622     20220211   20251016

[1 rows x 27 columns]
      obsnm             obsnmeng  wlobscd    mggvcd bbsncd  sbsncd  \
0  부산시(원동교)  Busansi(Wondonggyo)  2302650  기후에너지환경부  회야ㆍ수영  230203

     obsopndt obskdcd rivnm  bsnara  ...     tmx     tmy     gdt wltel tdeyn  \
0  2017-01-01     T/M  None  133.38  ...  392557  190653  -2.406  6.56     Y

  mxgrd sistartobsdh  siendobsdh olstartobsdh olendobsdh
0  None   2017010100  2025101622     20161231   20251016

[1 rows x 27 columns]
      obsnm            obsnmeng  wlobscd    mggvcd bbsncd  sbsncd    obsopndt  \
0  부산시(달음교)  Busansi(Daleumgyo)  2302651  기후에너지환경부  회야ㆍ수영  230201  2025-01-01

  obskdcd rivnm bsnara  ...     tmx     tmy     gdt   wltel tdeyn mxgrd  \
0     T/M   좌광천  22.46  ...  399839  204751  35.701  42.602     N  None

  sistartobsdh  siendobsdh olstartobsdh olendobsdh
0   2025010100  2025101622     20241231   20251016

[1 rows x 27 columns]
      obsnm              obsnmeng  wlobscd    mggvcd bbsncd  sbsncd  \
0  부산시(세병교)  Busansi(Sebyeonggyo)  2302655  기후에너지환경부  회야ㆍ수영  230203

     obsopndt obskdcd rivnm bsnara  ...     tmx     tmy    gdt wltel tdeyn  \
0  2022-03-02     T/M  None  39.53  ...  389691  190901  -1.34  8.17     N

  mxgrd sistartobsdh  siendobsdh olstartobsdh olendobsdh
0  None   2022021115  2025101622     20220211   20251016

[1 rows x 27 columns]
       obsnm                 obsnmeng  wlobscd    mggvcd bbsncd  sbsncd  \
0  부산시(좌수영교)  Busansi(jwarsuyounggyo)  2302661  기후에너지환경부  회야ㆍ수영  230203

     obsopndt obskdcd rivnm  bsnara  ...     tmx     tmy     gdt  wltel tdeyn  \
0  2024-01-09     T/M  None  190.48  ...  393210  188539  -3.415  2.891     N

  mxgrd sistartobsdh  siendobsdh olstartobsdh olendobsdh
0  None   2024020212  2025101622     20240202   20251016

[1 rows x 27 columns]
      obsnm                obsnmeng  wlobscd    mggvcd bbsncd  sbsncd  \
0  부산시(범천동)  Busansi(Beomcheondong)  2302670  기후에너지환경부  회야ㆍ수영  230205

     obsopndt obskdcd rivnm bsnara  ...     tmx     tmy     gdt  wltel tdeyn  \
0  2025-01-01     T/M    동천  26.38  ...  387850  185682  -1.782  3.764     N

  mxgrd sistartobsdh  siendobsdh olstartobsdh olendobsdh
0  None   2025010100  2025101622     20241231   20251016

[1 rows x 27 columns]
      obsnm          obsnmeng  wlobscd    mggvcd bbsncd  sbsncd    obsopndt  \
0  부산시(다대포)  Busansi(Dadaepo)  2302690  기후에너지환경부  회야ㆍ수영  230206  2022-04-20

  obskdcd rivnm bsnara  ...     tmx     tmy    gdt wltel tdeyn mxgrd  \
0     T/M   낙동강   None  ...  378397  175686  -1.43  4.31     N  None

  sistartobsdh  siendobsdh olstartobsdh olendobsdh
0   2022021412  2025101622     20220214   20251016

[1 rows x 27 columns]
      obsnm                obsnmeng  wlobscd   mggvcd bbsncd  sbsncd  \
0  부산시(신평동)  Busansi(Sinpyeongdong)  2302695  한국수자원공사  회야ㆍ수영  230206

     obsopndt obskdcd rivnm bsnara  ...     tmx     tmy    gdt  wltel tdeyn  \
0  1988-01-01     T/M  None  102.7  ...  378181  178950  -.345  4.588     Y

  mxgrd sistartobsdh  siendobsdh olstartobsdh olendobsdh
0   2.5   1987060120  2025101622     19870601   20251016

[1 rows x 27 columns]
       obsnm              obsnmeng  wlobscd    mggvcd bbsncd  sbsncd  \
0  울진군(올미골교)  Uljingun(Olmigolgyo)  2401613  기후에너지환경부  낙동강동해  240102

     obsopndt obskdcd rivnm  bsnara  ...     tmx     tmy    gdt  wltel tdeyn  \
0  2022-07-27     T/M   남대천  104.17  ...  406909  394964  49.84  55.31     N

  mxgrd sistartobsdh  siendobsdh olstartobsdh olendobsdh
0  None   2022072816  2025101622     20220728   20251016

[1 rows x 27 columns]
      obsnm               obsnmeng  wlobscd    mggvcd bbsncd  sbsncd  \
0  울진군(월변교)  Uljingun(Wolbyeongyo)  2401616  기후에너지환경부  낙동강동해  240102

     obsopndt obskdcd rivnm  bsnara  ...     tmx     tmy    gdt wltel tdeyn  \
0  2022-03-02     T/M   남대천  107.84  ...  413800  390476  2.392  27.3     N

  mxgrd sistartobsdh  siendobsdh olstartobsdh olendobsdh
0  None   2022021811  2025101622     20220218   20251016

[1 rows x 27 columns]
      obsnm           obsnmeng  wlobscd   mggvcd bbsncd  sbsncd    obsopndt  \
0  울진군(구산리)  Uljingun(Gusanri)  2401620  한국수자원공사  낙동강동해  240106  1996-12-26

  obskdcd rivnm bsnara  ...     tmx     tmy   gdt   wltel tdeyn mxgrd  \
0     T/M   왕피천  513.2  ...  411380  386281  8.39  13.329     N     6

  sistartobsdh  siendobsdh olstartobsdh olendobsdh
0   2002101511  2025101622     19990601   20251016

[1 rows x 27 columns]
       obsnm                obsnmeng  wlobscd    mggvcd bbsncd  sbsncd  \
0  영양군(수하3교)  Yeongyanggun(Suha3gyo)  2401633  기후에너지환경부  낙동강동해  240103

     obsopndt obskdcd rivnm  bsnara  ...     tmx     tmy      gdt    wltel  \
0  2024-01-09     T/M  장수포천  123.55  ...  402421  372550  291.597  300.356

  tdeyn mxgrd sistartobsdh  siendobsdh olstartobsdh olendobsdh
0     N  None   2024020212  2025101622     20240202   20251016

[1 rows x 27 columns]
      obsnm                obsnmeng  wlobscd    mggvcd bbsncd  sbsncd  \
0  울진군(천전교)  Uljingun(Cheonjeongyo)  2401640  기후에너지환경부  낙동강동해  240105

     obsopndt obskdcd rivnm  bsnara  ...     tmx     tmy    gdt   wltel tdeyn  \
0  2025-01-01     T/M    광천  174.15  ...  410925  388646  6.418  16.345     N

  mxgrd sistartobsdh  siendobsdh olstartobsdh olendobsdh
0  None   2025010100  2025101622     20241231   20251016

[1 rows x 27 columns]
      obsnm              obsnmeng  wlobscd    mggvcd bbsncd  sbsncd  \
0  울진군(기성교)  Uljingun(Giseonggyo)  2401641  기후에너지환경부  낙동강동해  240107

     obsopndt obskdcd rivnm bsnara  ...     tmx     tmy    gdt  wltel tdeyn  \
0  2025-01-01     T/M   척산천  60.33  ...  418618  368662  1.769  9.999     N

  mxgrd sistartobsdh  siendobsdh olstartobsdh olendobsdh
0  None   2025010100  2025101622     20241231   20251016

[1 rows x 27 columns]
      obsnm            obsnmeng  wlobscd    mggvcd bbsncd  sbsncd    obsopndt  \
0  울진군(수산교)  Uljingun(Susangyo)  2401650  기후에너지환경부  낙동강동해  240106  2017-01-01

  obskdcd rivnm  bsnara  ...     tmx     tmy     gdt wltel tdeyn mxgrd  \
0     T/M   왕피천  509.83  ...  413546  387786  -1.975  8.59     N  None

  sistartobsdh  siendobsdh olstartobsdh olendobsdh
0   2017010100  2025101622     20161231   20251016

[1 rows x 27 columns]
      obsnm               obsnmeng  wlobscd    mggvcd bbsncd  sbsncd  \
0  울진군(광품교)  Uljingun(Gwangpumgyo)  2401660  기후에너지환경부  낙동강동해  240108

     obsopndt obskdcd rivnm  bsnara  ...     tmx     tmy     gdt   wltel  \
0  2025-01-01     T/M   남대천  122.03  ...  415142  360829  19.551  26.336

  tdeyn mxgrd sistartobsdh  siendobsdh olstartobsdh olendobsdh
0     N  None   2025010100  2025101622     20241231   20251016

[1 rows x 27 columns]
      obsnm                  obsnmeng  wlobscd    mggvcd bbsncd  sbsncd  \
0  영덕군(인량교)  Yeongdeokgun(Illyanggyo)  2401690  기후에너지환경부  낙동강동해  240110

     obsopndt obskdcd rivnm bsnara  ...     tmx     tmy   gdt  wltel tdeyn  \
0  2016-01-01     T/M    송천  237.1  ...  412862  341582  6.44  13.29     N

  mxgrd sistartobsdh  siendobsdh olstartobsdh olendobsdh
0  None   2016010100  2025101622     20151231   20251016

[1 rows x 27 columns]
      obsnm                obsnmeng  wlobscd    mggvcd bbsncd  sbsncd  \
0  영덕군(만세교)  Yeongdeokgun(Mansegyo)  2402609  기후에너지환경부  낙동강동해  240202

     obsopndt obskdcd  rivnm bsnara  ...     tmx     tmy     gdt   wltel  \
0  2025-01-01     T/M  영덕오십천  90.39  ...  405468  329094  50.145  58.135

  tdeyn mxgrd sistartobsdh  siendobsdh olstartobsdh olendobsdh
0     N  None   2025010100  2025101622     20241231   20251016

[1 rows x 27 columns]
      obsnm               obsnmeng  wlobscd   mggvcd bbsncd  sbsncd  \
0  영덕군(대지리)  Yeongdeokgun(Daejiri)  2402620  한국수자원공사  낙동강동해  240203

     obsopndt obskdcd rivnm bsnara  ...     tmx     tmy    gdt  wltel tdeyn  \
0  1996-12-26     T/M   대서천  102.7  ...  407032  324133  55.84  60.98     N

  mxgrd sistartobsdh  siendobsdh olstartobsdh olendobsdh
0     5   2002120316  2025101622     19990601   20251016

[1 rows x 27 columns]
       obsnm                       obsnmeng  wlobscd    mggvcd bbsncd  sbsncd  \
0  영덕군(영덕대교)  Yeongdeokgun(Yeongdeokdaegyo)  2402630  기후에너지환경부  낙동강동해  240204

     obsopndt obskdcd  rivnm  bsnara  ...     tmx     tmy   gdt  wltel tdeyn  \
0  2016-01-01     T/M  영덕오십천  341.12  ...  412914  325325  3.66  11.45     N

  mxgrd sistartobsdh  siendobsdh olstartobsdh olendobsdh
0  None   2016010100  2025101622     20151231   20251016

[1 rows x 27 columns]
      obsnm              obsnmeng  wlobscd    mggvcd bbsncd  sbsncd  \
0  포항시(곡강교)  Pohangsi(Gokkanggyo)  2402680  기후에너지환경부  낙동강동해  240208

     obsopndt obskdcd rivnm bsnara  ...     tmx     tmy    gdt   wltel tdeyn  \
0  2024-01-09     T/M   곡강천  96.17  ...  411226  294126  9.466  15.902     N

  mxgrd sistartobsdh  siendobsdh olstartobsdh olendobsdh
0  None   2024010100  2025101622     20231231   20251016

[1 rows x 27 columns]
      obsnm               obsnmeng  wlobscd    mggvcd bbsncd  sbsncd  \
0  포항시(문충교)  Pohangsi(Munchunggyo)  2403617  기후에너지환경부  낙동강동해  240302

     obsopndt obskdcd rivnm bsnara  ...     tmx     tmy     gdt  wltel tdeyn  \
0  2025-01-01     T/M    냉천   23.3  ...  416633  272787  51.474  58.23     N

  mxgrd sistartobsdh  siendobsdh olstartobsdh olendobsdh
0  None   2025010100  2025101622     20241231   20251016

[1 rows x 27 columns]
       obsnm               obsnmeng  wlobscd    mggvcd bbsncd  sbsncd  \
0  포항시(문덕2교)  Pohangsi(Mundeok2gyo)  2403618  기후에너지환경부  낙동강동해  240302

     obsopndt obskdcd rivnm bsnara  ...     tmx     tmy     gdt   wltel tdeyn  \
0  2025-01-01     T/M   신광천  28.61  ...  415922  274158  47.341  53.895     N

  mxgrd sistartobsdh  siendobsdh olstartobsdh olendobsdh
0  None   2025010100  2025101622     20241231   20251016

[1 rows x 27 columns]
       obsnm               obsnmeng  wlobscd    mggvcd bbsncd  sbsncd  \
0  포항시(문덕3교)  Pohangsi(Mundeok3gyo)  2403620  기후에너지환경부  낙동강동해  240302

     obsopndt obskdcd rivnm bsnara  ...     tmx     tmy     gdt  wltel tdeyn  \
0  2023-03-05     T/M    냉천   60.1  ...  417121  275359  26.894  36.38     N

  mxgrd sistartobsdh  siendobsdh olstartobsdh olendobsdh
0  None   2023042710  2025101622     20230427   20251016

[1 rows x 27 columns]
      obsnm              obsnmeng  wlobscd    mggvcd bbsncd  sbsncd  \
0  경주시(구길교)  Gyeongjusi(Gugilgyo)  2403625  기후에너지환경부  낙동강동해  240304

     obsopndt obskdcd rivnm  bsnara  ...     tmx     tmy   gdt wltel tdeyn  \
0  2023-01-09     T/M   대종천  110.32  ...  423024  253141  4.74  13.5     N

  mxgrd sistartobsdh  siendobsdh olstartobsdh olendobsdh
0  None   2023010900  2025101622     20230108   20251016

[1 rows x 27 columns]
      obsnm               obsnmeng  wlobscd    mggvcd bbsncd  sbsncd  \
0  울산시(신명교)  Ulsansi(Sinmyeonggyo)  2403660  기후에너지환경부  낙동강동해  240306

     obsopndt obskdcd rivnm bsnara  ...     tmx     tmy    gdt  wltel tdeyn  \
0  2025-01-01     T/M   신명천  18.83  ...  420992  240812  -.239  5.445     N

  mxgrd sistartobsdh  siendobsdh olstartobsdh olendobsdh
0  None   2025010100  2025101622     20241231   20251016

[1 rows x 27 columns]
  obsnm      obsnmeng  wlobscd   mggvcd bbsncd  sbsncd    obsopndt obskdcd  \
0    판문  NAM GANG DAM  2501620  한국수자원공사    낙동강  201814  1995-01-01     T/M

  rivnm bsnara  ...     tmx     tmy   gdt wltel tdeyn mxgrd sistartobsdh  \
0  None   2285  ...  293851  187242  26.5     0     N  22.7   1987060120

   siendobsdh olstartobsdh olendobsdh
0  2019081415     20010101   20190814

[1 rows x 27 columns]
      obsnm              obsnmeng  wlobscd    mggvcd bbsncd  sbsncd  \
0  사천시(솥골교)  Sacheonsi(Sotgolgyo)  2501630  기후에너지환경부  낙동강남해  250102

     obsopndt obskdcd rivnm bsnara  ...     tmx     tmy    gdt   wltel tdeyn  \
0  2025-01-01     T/M   곤양천  53.81  ...  287927  174330  3.386  10.275     N

  mxgrd sistartobsdh  siendobsdh olstartobsdh olendobsdh
0  None   2025010100  2025101622     20241231   20251016

[1 rows x 27 columns]
      obsnm               obsnmeng  wlobscd    mggvcd bbsncd  sbsncd  \
0  남해군(금서교)  Namhaegun(Geumseogyo)  2502610  기후에너지환경부  낙동강남해  250201

     obsopndt obskdcd rivnm bsnara  ...     tmx     tmy    gdt  wltel tdeyn  \
0  2025-01-01     T/M   서상천  15.98  ...  277190  146372  1.646  6.745     N

  mxgrd sistartobsdh  siendobsdh olstartobsdh olendobsdh
0  None   2025010100  2025101622     20241231   20251016

[1 rows x 27 columns]
      obsnm                 obsnmeng  wlobscd    mggvcd bbsncd  sbsncd  \
0  남해군(봉천교)  Namhaegun(Bongcheongyo)  2502630  기후에너지환경부  낙동강남해  250202

     obsopndt obskdcd rivnm bsnara  ...     tmx     tmy    gdt  wltel tdeyn  \
0  2025-01-01     T/M    봉천   3.19  ...  282075  148756  8.631  12.65     N

  mxgrd sistartobsdh  siendobsdh olstartobsdh olendobsdh
0  None   2025010100  2025101622     20241231   20251016

[1 rows x 27 columns]
      obsnm               obsnmeng  wlobscd    mggvcd bbsncd  sbsncd  \
0  남해군(봉화교)  Namhaegun(Bonghwagyo)  2502660  기후에너지환경부  낙동강남해  250204

     obsopndt obskdcd rivnm bsnara  ...     tmx     tmy     gdt  wltel tdeyn  \
0  2025-01-01     T/M    화천  22.54  ...  294529  146072  10.408  16.51     N

  mxgrd sistartobsdh  siendobsdh olstartobsdh olendobsdh
0  None   2025010100  2025101622     20241231   20251016

[1 rows x 27 columns]
      obsnm             obsnmeng  wlobscd   mggvcd bbsncd  sbsncd    obsopndt  \
0  거제시(연초댐)  Geojesi(Yeonchodam)  2503620  한국수자원공사  낙동강남해  250302  1979-12-31

  obskdcd rivnm bsnara  ...   tmx   tmy   gdt wltel tdeyn mxgrd sistartobsdh  \
0     T/M   연초천   11.7  ...  None  None  None  None     N    15   2019013013

   siendobsdh olstartobsdh olendobsdh
0  2025101622     20190129   20251016

[1 rows x 27 columns]
       obsnm             obsnmeng  wlobscd    mggvcd bbsncd  sbsncd  \
0  거제시(덕포2교)  Geojesi(Deokpo2gyo)  2503623  기후에너지환경부  낙동강남해  250303

     obsopndt obskdcd rivnm bsnara  ...     tmx     tmy   gdt  wltel tdeyn  \
0  2025-01-01     T/M   덕포천   3.06  ...  355774  158406  4.96  9.439     N

  mxgrd sistartobsdh  siendobsdh olstartobsdh olendobsdh
0  None   2025010100  2025101622     20241231   20251016

[1 rows x 27 columns]
      obsnm             obsnmeng  wlobscd   mggvcd bbsncd  sbsncd    obsopndt  \
0  거제시(죽전교)  Geojesi(Jukjeongyo)  2503625  한국수자원공사  낙동강남해  250304  2008-03-13

  obskdcd rivnm bsnara  ...     tmx     tmy   gdt wltel tdeyn mxgrd  \
0     T/M   둔덕천   17.7  ...  338545  150761  None  None     N     5

  sistartobsdh  siendobsdh olstartobsdh olendobsdh
0   2015071400  2025101622     2          20251016

[1 rows x 27 columns]
      obsnm             obsnmeng  wlobscd    mggvcd bbsncd  sbsncd  \
0  거제시(독봉교)  Geojesi(Dokbonggyo)  2503635  기후에너지환경부  낙동강남해  250302

     obsopndt obskdcd rivnm bsnara  ...     tmx     tmy    gdt   wltel tdeyn  \
0  2025-01-01     T/M   고현천  10.81  ...  349333  154691  8.301  15.004     N

  mxgrd sistartobsdh  siendobsdh olstartobsdh olendobsdh
0  None   2025010100  2025101622     20241231   20251016

[1 rows x 27 columns]
      obsnm             obsnmeng  wlobscd   mggvcd bbsncd  sbsncd    obsopndt  \
0  거제시(구천댐)  Geojesi(GuCheonDam)  2503640  한국수자원공사  낙동강남해  250304  1987-12-31

  obskdcd rivnm bsnara  ...     tmx     tmy gdt wltel tdeyn mxgrd  \
0     T/M   구천천   None  ...  349661  148623   0  None     N    95

  sistartobsdh  siendobsdh olstartobsdh olendobsdh
0   2020021114  2025101622     20200101   20251016

[1 rows x 27 columns]
      obsnm             obsnmeng  wlobscd   mggvcd bbsncd  sbsncd    obsopndt  \
0  거제시(구천교)  Geojesi(Gugheongyo)  2503650  한국수자원공사  낙동강남해  250304  2008-01-01

  obskdcd rivnm bsnara  ...   tmx   tmy   gdt wltel tdeyn mxgrd sistartobsdh  \
0     T/M   구천천   12.7  ...  None  None  None  None     N     3   2007111220

   siendobsdh olstartobsdh olendobsdh
0  2025101622     20071112   20251016

[1 rows x 27 columns]
       obsnm                obsnmeng  wlobscd    mggvcd bbsncd  sbsncd  \
0  창원시(진북2교)  Changwonsi(Jinbuk2gyo)  2504655  기후에너지환경부  낙동강남해  250405

     obsopndt obskdcd rivnm bsnara  ...     tmx     tmy     gdt   wltel tdeyn  \
0  2025-01-01     T/M   진동천  17.89  ...  335214  183388  18.532  26.427     N

  mxgrd sistartobsdh  siendobsdh olstartobsdh olendobsdh
0  None   2025010100  2025101622     20241231   20251016

[1 rows x 27 columns]
          obsnm                obsnmeng  wlobscd    mggvcd bbsncd  sbsncd  \
0  창원시(창원천제1호교)  Changwoncheonje1hogyo)  2504660  기후에너지환경부  낙동강남해  250407

     obsopndt obskdcd rivnm bsnara  ...     tmx     tmy    gdt   wltel tdeyn  \
0  2025-01-01     T/M  None     12  ...  351520  195670  4.448  10.498     N

  mxgrd sistartobsdh  siendobsdh olstartobsdh olendobsdh

In [6]:
vv.reset_index(drop=True,inplace=True)

In [7]:
got=vv[['obsnm','wlobscd','tmx','tmy']]
got.dropna(axis=0,inplace=True)

/tmp/ipython-input-1119914289.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  got.dropna(axis=0,inplace=True)

# 관측소 좌표변환

In [72]:
got

         obsnm  wlobscd     tmx     tmy         lon        lat
0     평창군(송정교)  1001602  336935  459417  120.992317  23.960876
1     태백시(무사교)  1001603  376803  425838  121.395987  23.675392
2         송천1교  1001605  350849  464532  121.125942  24.012515
3     삼척시(번천교)  1001607  376860  431330  121.394240  23.724738
4     삼척시(광동교)  1001613  372665  430594  121.353631  23.716502
...        ...      ...     ...     ...         ...        ...
1182  고창군(부정교)  5301660  165839  219581  119.452898  21.735976
1183  고창군(용선교)  5301690  163268  225910  119.425095  21.791382
1184  영광군(반와교)  5302620  155189  202308  119.359672  21.576478
1185        불갑  5302640  155265  192198  119.365470  21.486094
1186  영광군(외간교)  5302660  151410  194838  119.327306  21.507894

[1177 rows x 6 columns]

In [89]:
tm_proj = Proj(init='epsg:2097')   # TM 좌표
wgs84_proj = Proj(proj='latlong', datum='WGS84')  # 위경도

# 변환기 생성
transformer = Transformer.from_proj(tm_proj, wgs84_proj)

# 변환 수행
got['lon'], got['lat'] = transformer.transform(got['tmx'].values, got['tmy'].values)

/usr/local/lib/python3.12/dist-packages/pyproj/crs/crs.py:143: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  in_crs_string = _prepare_from_proj_string(in_crs_string)
/tmp/ipython-input-2254988868.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  got['lon'], got['lat'] = transformer.transform(got['tmx'].values, got['tmy'].values)

In [90]:
adj = pd.read_csv('/content/drive/MyDrive/지하수예측경진대회/12개_지하수_지점_정보.csv')

In [91]:
adj=adj[['code_new','위도','경도','수리전도도(cm/sec)','표고(EL.m)']]

In [92]:
obs=got[['wlobscd','lon','lat']]

In [93]:
# 시작과 종료 날짜
start_date = pd.to_datetime('20140101')
end_date = pd.to_datetime('20231231')

start_list = []
end_list = []

current_start = start_date

while current_start <= end_date:
    current_end = current_start + pd.DateOffset(months=6) - pd.Timedelta(days=1)
    if current_end > end_date:
        current_end = end_date

    start_list.append(current_start.strftime('%Y%m%d'))
    end_list.append(current_end.strftime('%Y%m%d'))

    current_start = current_end + pd.Timedelta(days=1)

In [94]:
eleven = []

for node in tqdm(range(0, 12)):
    for k in tqdm(range(1, 20)):  # k번째로 가까운 관측소
        obs_coords = obs[['lat', 'lon']].to_numpy()
        tree = cKDTree(obs_coords)

        # adj 좌표
        adj_coords = adj.loc[node, ['위도', '경도']].to_numpy()

        # k번째로 가까운 관측소 찾기
        distances, indices = tree.query(adj_coords, k=k)
        if k == 1:
            second_distances = distances
            second_indices = indices
        else:
            second_distances = distances[k - 1]
            second_indices = indices[k - 1]

        # adj에 wlobscd, distance 추가
        adj.loc[node, 'wlobscd'] = obs.iloc[second_indices]['wlobscd']
        adj.loc[node, 'distance'] = second_distances

        node_dfs = []
        data_found = False

        for time in range(len(start_list)):
            params = {
                "obscd": adj['wlobscd'][node],
                "startdt": start_list[time],
                "enddt": end_list[time],
                "output": "json"
            }

            url = 'http://www.wamis.go.kr:8080/wamis/openapi/wkw/wl_hrdata'
            response = requests.get(url, params=params)

            if response.status_code == 200:
                data = response.json()
                obs_list = data.get("list", [])

                if len(obs_list) > 0:
                    df = pd.DataFrame(obs_list)
                    node_dfs.append(df)
            else:
                print(f"API 요청 실패: {response.status_code}")

        # time별 DataFrame 합치기
        if len(node_dfs) > 0:
            node_df = pd.concat(node_dfs, axis=0, ignore_index=True, sort=False)

            # 길이가 80000 이상이면 append, 아니면 다음 k
            if len(node_df) > 80000:
                eleven.append(node_df)
                break  # 조건 만족했으므로 k 루프 종료
            else:
                # 다음 k 시도
                continue

  0%|          | 0/12 [00:00<?, ?it/s]
  0%|          | 0/19 [00:49<?, ?it/s]
  8%|▊         | 1/12 [00:49<09:02, 49.31s/it]
  0%|          | 0/19 [00:57<?, ?it/s]
 17%|█▋        | 2/12 [01:46<09:00, 54.08s/it]
  0%|          | 0/19 [00:29<?, ?it/s]
 25%|██▌       | 3/12 [02:16<06:25, 42.80s/it]
  0%|          | 0/19 [00:21<?, ?it/s]
 33%|███▎      | 4/12 [02:37<04:35, 34.40s/it]
  0%|          | 0/19 [00:22<?, ?it/s]
 42%|████▏     | 5/12 [02:59<03:29, 29.94s/it]
  0%|          | 0/19 [00:00<?, ?it/s]
  5%|▌         | 1/19 [00:42<12:36, 42.02s/it]
 50%|█████     | 6/12 [03:41<03:24, 34.05s/it]
  0%|          | 0/19 [00:30<?, ?it/s]
 58%|█████▊    | 7/12 [04:12<02:44, 32.87s/it]
  0%|          | 0/19 [00:24<?, ?it/s]
 67%|██████▋   | 8/12 [04:36<02:00, 30.24s/it]
  0%|          | 0/19 [00:21<?, ?it/s]
 75%|███████▌  | 9/12 [04:58<01:22, 27.58s/it]
  0%|          | 0/19 [00:00<?, ?it/s]
  5%|▌         | 1/19 [00:30<09:07, 30.40s/it]
 83%|████████▎ | 10/12 [05:28<00:56, 28.45s/it]
  0%|          | 0/19 [00:00<?, ?it/s]
  5%|▌         | 1/19 [00:29<08:50, 29.50s/it]
 92%|█████████▏| 11/12 [05:58<00:28, 28.77s/it]
  0%|          | 0/19 [00:01<?, ?it/s]
 92%|█████████▏| 11/12 [05:59<00:32, 32.69s/it]

KeyboardInterrupt:

In [96]:
adj=pd.merge(got[['obsnm','lon','lat','wlobscd']],adj,on='wlobscd',how='right')

In [99]:
adj.to_csv('/content/drive/MyDrive/지하수예측경진대회/12개_지하수_지점_정보.csv',index=False)

In [104]:
eleven[0]

             ymdh    wl  code_new
0      2014010101   .35         1
1      2014010102   .35         1
2      2014010103   .35         1
3      2014010104   .35         1
4      2014010105   .35         1
...           ...   ...       ...
87516  2023123120  1.27         1
87517  2023123121  1.27         1
87518  2023123122  1.27         1
87519  2023123123  1.27         1
87520  2023123124  1.27         1

[87521 rows x 3 columns]

In [106]:
for node in range(12):
# 리스트의 DataFrame을 하나로 합치기
# bb 안에 리스트가 들어있는 경우 flatten
    final_df = pd.concat(eleven, axis=0, ignore_index=True)

In [107]:
final_df

              ymdh    wl  code_new
0       2014010101   .35         1
1       2014010102   .35         1
2       2014010103   .35         1
3       2014010104   .35         1
4       2014010105   .35         1
...            ...   ...       ...
944651  2023123120  1.31        11
944652  2023123121  1.32        11
944653  2023123122  1.33        11
944654  2023123123  1.32        11
944655  2023123124  1.33        11

[944656 rows x 3 columns]

In [108]:
# ymdh가 2023123124인 행 제거
final_df = final_df[final_df['ymdh'] != '2023123124']

In [109]:
# 문자열 길이 10자리만 사용
final_df['ymdh_fixed'] = final_df['ymdh'].str[:10]
# datetime 변환
final_df['ymd'] = pd.to_datetime(final_df['ymdh_fixed'], format='%Y%m%d%H', errors='coerce')

/tmp/ipython-input-4047605523.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df['ymdh_fixed'] = final_df['ymdh'].str[:10]
/tmp/ipython-input-4047605523.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df['ymd'] = pd.to_datetime(final_df['ymdh_fixed'], format='%Y%m%d%H', errors='coerce')

In [110]:
final_df.drop(['ymdh_fixed','ymdh'],axis=1,inplace=True)

/tmp/ipython-input-3417081849.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df.drop(['ymdh_fixed','ymdh'],axis=1,inplace=True)

In [111]:
df_no_dup = final_df.sort_values(by=['code_new','ymd'],ascending=True)

In [112]:
df = df_no_dup[df_no_dup['ymd'].notna()]

In [114]:
df.to_csv('/content/drive/MyDrive/지하수예측경진대회/근처하천수위.csv',index=False)